### ISSUE TITLE
[BUG]用这个方法Usage (Run from Python Source Code)运行好像会报错了，我找了半天发现要把pip install -r requirements.txt里的ok script改回0.0.185版本才行，不过看不懂错误代码不知道具体哪里不行

### ISSUE THREAD

**Issue by ggxfwin** [ok-oldking/ok-wuthering-waves#112]
2024-09-06 13:59:14,446 ERROR MainThread OK:__init__ error Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ok\OK.py", line 62, in __init__
    self.do_init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ok\OK.py", line 121, in do_init
    self.task_executor = TaskExecutor(self.device_manager, exit_event=self.exit_event,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ok\task\TaskExecutor.py", line 68, in __init__
    self.trigger_tasks = self.init_tasks(trigger_tasks)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ok\task\TaskExecutor.py", line 76, in init_tasks
    task = init_class_by_name(task_class[0], task_class[1])
                              ~~~~~~~~~~^^^
TypeError: type 'AutoCombatTask' is not subscriptable

**Comment by ok-oldking** [comment]
对 先用老版本的 最近还在改
