### ISSUE TITLE
[BUG] 使用源代码运行gpu版本时无法运行

### ISSUE THREAD

**Issue by Master-Tan** [ok-oldking/ok-wuthering-waves#120]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
使用源代码运行gpu版本时无法运行

复现步骤 按照以下步骤复现行为：

1. 
git clone https://github.com/ok-oldking/ok-wuthering-waves
(python版本为3.11.9)
pip install -r requirements.txt 
python main_gpu.py 

2. 
报错 
2024-09-23 13:41:52,472 ERROR MainThread OK:__init__ error Traceback (most recent call last):
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 62, in __init__
    self.do_init()
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 138, in do_init
    from paddleocr import PaddleOCR
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

截图 :
无

是否必现:
是

录屏:
无

脚本软件版本：
[如]1.1.1

windows操作系统:
Windows 10

上传日志:

2024-09-23 13:41:52,349 INFO TaskExecutor TaskExecutor:start execute
2024-09-23 13:41:52,349 INFO MainThread OK:use paddleocr as ocr lib
2024-09-23 13:41:52,349 INFO TaskExecutor TaskExecutor:executor is paused sleep
Traceback (most recent call last):
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 62, in __init__
    self.do_init()
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 138, in do_init
    from paddleocr import PaddleOCR
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'
2024-09-23 13:41:52,472 ERROR MainThread OK:__init__ error Traceback (most recent call last):
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 62, in __init__
    self.do_init()
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\ok\OK.py", line 138, in do_init
    from paddleocr import PaddleOCR
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "D:\PycharmProjects\ok-wuthering-waves\venv\Lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

**Comment by YCR160** [comment]
先运行 `python launcher.py` 安装相关依赖，或者手动安装：
https://github.com/ok-oldking/ok-wuthering-waves/blob/9aad36c95c8a897a3a333f7345e88a1ce4968901/launcher.json#L6-L10

**Comment by ok-oldking** [comment]
按照requirements-gpu.txt里安装依赖
