### ISSUE TITLE
[BUG] 刷新BOSS报错

### ISSUE THREAD

**Issue by Canda15** [ok-oldking/ok-wuthering-waves#129]
![图片](https://github.com/user-attachments/assets/bd12ad91-be50-4486-a1b1-8e77a87f0b34)
![图片](https://github.com/user-attachments/assets/96fa1ad1-b234-4e4d-89d4-d68be65a1e78)

https://github.com/user-attachments/assets/3d822599-c5b9-4dda-acf3-cb00aebe990d

**Comment by Canda15** [comment]
`2024-09-29 20:11:10,371 INFO ok.gui.StartController HwndWindow:find_hwnd [(2820196, 'E:\\Game\\Wuthering Waves\\Wuthering Waves Game\\Client\\Binaries\\Win64\\Client-Win64-Shipping.exe', 1920, 1080, 0, 0, '鸣潮  ')]
2024-09-29 20:11:10,406 INFO ok.gui.StartController HwndWindow:find_hwnd [(2820196, 'E:\\Game\\Wuthering Waves\\Wuthering Waves Game\\Client\\Binaries\\Win64\\Client-Win64-Shipping.exe', 1920, 1080, 0, 0, '鸣潮  ')]
2024-09-29 20:11:10,407 INFO ok.gui.StartController HwndWindow:found hwnd 2820196 E:\Game\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\Client-Win64-Shipping.exe UnrealWindow real:0,0,0,0
2024-09-29 20:11:10,412 INFO ok.gui.StartController DeviceManager:capture method <class 'ok.capture.windows.WindowsGraphicsCaptureMethod.WindowsGraphicsCaptureMethod'>
2024-09-29 20:11:10,413 INFO ok.gui.StartController StartController:start checking for night light
2024-09-29 20:11:10,415 INFO ok.gui.StartController display:is_night_light_enabled is False
2024-09-29 20:11:11,604 INFO TaskExecutor FarmWorldBossTask:teleport to Fallacy of No Return index 6 in_dungeon False
2024-09-29 20:11:12,706 INFO TaskExecutor FarmWorldBossTask:click f2 to open the book
2024-09-29 20:11:14,833 INFO TaskExecutor FarmWorldBossTask:click Box(name='gray_book_all_monsters', x=40, y=535, width=78, height=80, confidence=97)
2024-09-29 20:11:18,356 INFO TaskExecutor BaseWWTask:scroll down a page
2024-09-29 20:11:21,199 INFO TaskExecutor FarmWorldBossTask:index after scrolling down 6
2024-09-29 20:11:32,448 INFO TaskExecutor TaskExecutor:wait_until timeout <function FindFeature.wait_click_feature.<locals>.<lambda> at 0x0000029E981E6200> 5 seconds
2024-09-29 20:11:32,470 ERROR TaskExecutor TaskExecutor:Farm World Boss(Must Drop a WayPoint on the Boss First) exception Traceback (most recent call last):
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\task\TaskExecutor.py", line 297, in execute
    self.current_task.run()
  File "E:\1\ok-ww\repo\v0.3.82\src\task\FarmWorldBossTask.py", line 99, in run
    self.teleport_to_boss(boss_name)
  File "E:\1\ok-ww\repo\v0.3.82\src\task\BaseWWTask.py", line 361, in teleport_to_boss
    self.wait_click_travel()
  File "E:\1\ok-ww\repo\v0.3.82\src\task\BaseWWTask.py", line 375, in wait_click_travel
    self.wait_until(self.click_traval_button, raise_if_not_found=True, time_out=10)
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\task\ExecutorOperation.py", line 281, in wait_until
    return self.executor.wait_condition(condition, time_out, pre_action, post_action, wait_until_before_delay,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\task\TaskExecutor.py", line 227, in wait_condition
    result = condition()
             ^^^^^^^^^^^
  File "E:\1\ok-ww\repo\v0.3.82\src\task\BaseWWTask.py", line 368, in click_traval_button
    return self.wait_click_feature('gray_confirm_exit_button', relative_x=-1, raise_if_not_found=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\feature\FindFeature.py", line 60, in wait_click_feature
    box = self.wait_until(
          ^^^^^^^^^^^^^^^^
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\task\ExecutorOperation.py", line 281, in wait_until
    return self.executor.wait_condition(condition, time_out, pre_action, post_action, wait_until_before_delay,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\1\ok-ww\python\app_env\Lib\site-packages\ok\task\TaskExecutor.py", line 240, in wait_condition
    raise WaitFailedException()
ok.task.TaskExecutor.WaitFailedException

`

**Comment by ok-oldking** [comment]
更新
