### ISSUE TITLE
[BUG]无法正常的进行下载安装

### ISSUE THREAD

**Issue by Mikygz49** [ok-oldking/ok-wuthering-waves#180]
请先挨个检查:
[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/blob/master/README_cn.md#出现问题请检查)

搜索现有ISSUE:
[https://github.com/ok-oldking/ok-wuthering-waves/issues?q=](https://github.com/ok-oldking/ok-wuthering-waves/issues?q=)

描述错误:
[请清晰简洁地描述错误是什么]
卡安装进度，换了几个安装源都是一样的效果，挂梯子下载也无法解决，等待了一个小时也没有成功进软件，安装路径也是全英文，没有直接解压在下载路径中
复现步骤 按照以下步骤复现行为：

1. 点击 ‘…’
2. 向下滚动到 ‘…’
3. 看到错误

截图 :
如果适用，添加截图以帮助解释您的问题。
![{10EB9296-F6B0-41da-9011-8678783B210E}](https://github.com/user-attachments/assets/c3c67bc7-04c2-4c32-bb37-63eaebef023f)
![{35215BEF-84A8-40d6-81B7-3787017E3017}](https://github.com/user-attachments/assets/a9d72180-cc4c-421c-acf4-77d103055fd3)

是否必现:
是/否/大概率/小概率
是
录屏:
最好有录屏上传QQ频道

脚本软件版本：
[如]1.1.1

windows操作系统:
[例如] Windows 11 Pro 23H2 22631.3593

上传日志:
将脚本安装目录的logs,screenshots打包上传附件

**Comment by sereinna** [comment]
+1 same question

**Comment by ok-oldking** [comment]
上传日志

**Comment by nisests** [comment]
今天不知道为什么一直卡在这个页面   看了只有ok-script.log有报错

2024-12-11 18:40:07,596 INFO MainThread OK:AutoHelper init, config: {'debug': False, 'use_gui': True, 'config_folder': 'configs', 'gui_icon': 'icon.png', 'ocr': {'lib': 'paddleocr'}, 'start_timeout': 120, 'wait_until_before_delay': 2, 'template_matching': {'coco_feature_json': 'assets\\result.json', 'default_horizontal_variance': 0.002, 'default_vertical_variance': 0.002, 'default_threshold': 0.8}, 'windows': {'exe': 'Client-Win64-Shipping.exe', 'calculate_pc_exe_path': <function calculate_pc_exe_path at 0x00000208FD4F8E00>, 'hwnd_class': 'UnrealWindow', 'interaction': 'PostMessage', 'can_bit_blt': True, 'bit_blt_render_full': True, 'check_hdr': False, 'force_no_hdr': False, 'check_night_light': True, 'force_no_night_light': False, 'require_bg': True}, 'window_size': {'width': 800, 'height': 600, 'min_width': 600, 'min_height': 450}, 'supported_resolution': {'ratio': '16:9', 'min_size': (1280, 720)}, 'analytics': {'report_url': 'http://111.231.71.225/report'}, 'git_update': {'sources': [{'name': 'Global', 'git_url': 'https://github.com/ok-oldking/ok-ww-update.git', 'pip_url': 'https://pypi.org/simple/'}, {'name': '清华大学', 'git_url': 'https://e.coding.net/g-frfh1513/ok-wuthering-waves/ok-wuthering-waves.git', 'pip_url': 'https://pypi.tuna.tsinghua.edu.cn/simple'}, {'name': 'China', 'git_url': 'https://e.coding.net/g-frfh1513/ok-wuthering-waves/ok-wuthering-waves.git', 'pip_url': 'https://pypi.tuna.tsinghua.edu.cn/simple'}, {'name': '腾讯云', 'git_url': 'https://e.coding.net/g-frfh1513/ok-wuthering-waves/ok-wuthering-waves.git', 'pip_url': 'https://mirrors.cloud.tencent.com/pypi/simple'}, {'name': '阿里云', 'git_url': 'https://e.coding.net/g-frfh1513/ok-wuthering-waves/ok-wuthering-waves.git', 'pip_url': 'https://mirrors.aliyun.com/pypi/simple'}]}, 'links': {'default': {'github': 'https://github.com/ok-oldking/ok-wuthering-waves', 'faq': 'https://github.com/ok-oldking/ok-wuthering-waves#FAQ'}, 'zh_CN': {'github': 'https://github.com/ok-oldking/ok-wuthering-waves', 'faq': 'https://gitee.com/ok-olding/ok-wuthering-waves/blob/master/README_cn.md#%E5%87%BA%E7%8E%B0%E9%97%AE%E9%A2%98%E8%AF%B7%E6%A3%80%E6%9F%A5'}}, 'about': '\n    <h3>OK-WW</h3>\n    <p>GitHub <a href="https://github.com/ok-oldking/ok-wuthering-waves">https://github.com/ok-oldking/ok-wuthering-waves</></p>\n    <p>Report a BUG <a href="https://github.com/ok-oldking/ok-wuthering-waves/issues/new?assignees=ok-oldking&labels=bug&projects=&template=%E6%8A%A5%E5%91%8Abug-.md&title=%5BBUG%5D">https://github.com/ok-oldking/ok-wuthering-waves/issues/new?assignees=ok-oldking&labels=bug&projects=&template=%E6%8A%A5%E5%91%8Abug-.md&title=%5BBUG%5D</></p>\n    <p>QQ群:<a href="https://qm.qq.com/q/qMezq2IDGU">970523295</a></p>\n    <p>QQ频道:<a href="https://pd.qq.com/s/75758wrmp">OK-WW</a></p>\n    <p style="color:red;">\n    <strong>本软件是免费开源的。</strong> 如果你被收费，请立即退款。请访问QQ频道或GitHub下载最新的官方版本。\n    </p>\n    <p style="color:red;">\n        <strong>本软件仅供个人使用，用于学习Python编程、计算机视觉、UI自动化等。</strong> 请勿将其用于任何营利性或商业用途。\n    </p>\n    <p style="color:red;">\n        <strong>使用本软件可能会导致账号被封。</strong> 请在了解风险后再使用。\n    </p>\n', 'screenshots_folder': 'screenshots', 'gui_title': 'OK-WW', 'log_file': 'logs/ok-ww.log', 'error_log_file': 'logs/ok-ww_error.log', 'launcher_log_file': 'logs/launcher.log', 'launcher_error_log_file': 'logs/launcher_error.log', 'version': 'v1.4.58', 'onetime_tasks': [['src.task.FarmEchoTask', 'FarmEchoTask'], ['src.task.FarmWorldBossTask', 'FarmWorldBossTask'], ['src.task.DiscardEchoTask', 'DiscardEchoTask'], ['src.task.DiagnosisTask', 'DiagnosisTask']], 'trigger_tasks': [['src.task.AutoCombatTask', 'AutoCombatTask'], ['src.task.AutoPickTask', 'AutoPickTask'], ['src.task.SkipDialogTask', 'AutoDialogTask'], ['src.task.MouseResetTask', 'MouseResetTask'], ['src.task.AutoLoginTask', 'AutoLoginTask']]}
2024-12-11 18:40:07,806 INFO MainThread OK:SetProcessDpiAwareness 0
2024-12-11 18:40:07,893 ERROR MainThread OK:__init__ error Traceback (most recent call last):
  File "ok\\OK.pyx", line 52, in ok.OK.OK.__init__
  File "ok\\OK.pyx", line 197, in ok.OK.OK.init_device_manager
  File "ok\\Capture.pyx", line 22, in init ok.Capture
ModuleNotFoundError: No module named 'ok.color.Color'

**Comment by ok-oldking** [comment]
目录加杀毒软件白名单
