### ISSUE TITLE
[BUG]当第一次启动时挂着梯子会报http链接错误

### ISSUE THREAD

**Issue by lin-xiaosheng** [ok-oldking/ok-wuthering-waves#21]
关闭梯子并重新打开即可。日志如下-------------------
2024-07-23 23:02:34,651 ERROR ok.firebase.Analytics Handler:handler ok.firebase.Analytics raised exception Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 464, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 464, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ok\util\Handler.py", line 44, in _process_tasks
  File "ok\firebase\Analytics.py", line 108, in send_alive
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2024-07-23 23:04:33,370 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-23 23:06:35,065 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-23 23:06:52,960 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-23 23:07:09,557 ERROR TaskExecutor CombatCheck:target_enemy failed, break out of combat 
2024-07-23 23:07:09,579 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-23 23:11:40,126 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-23 23:11:49,421 ERROR TaskExecutor BaseCombatTask:combat check not in combat 

PS:
排查了各种原因，最后查log发现好像是梯子的问题.....

**Comment by ok-oldking** [comment]
没什么影响 上报日活数据的
