### ISSUE TITLE
会自动停止运行[BUG]

### ISSUE THREAD

**Issue by kunkun9527** [ok-oldking/ok-wuthering-waves#3]
描述错误:
跑了几天，都不能顺畅的打100只怪以上。有时候10只后会自动停止，有时候50只，很不稳定。

比如刷无妄者，每次脚本停止运行时，就会停留在刚副本出来后的位置，站在原地不动。检查日志，发现每次停止运行，“cant find the f to enter”这个错误都会出现。

另外，还有一个问题，就是晚上挂机的时候，月卡奖励跳出来后，脚本也会停止（我不确定是否这个原因，但每次起床检查，发现都是停在了月卡这个界面）。

脚本软件版本：
最新

上传日志:
2024-07-12 13:25:49,608 ERROR TaskExecutor BaseCombatTask:not in team while switching chars_Jinhsi_T_to_Verina_F, 0.0 
2024-07-12 13:27:11,978 ERROR TaskExecutor BaseCombatTask:not in team while switching chars_Jinhsi_T_to_Verina_F, 0.0 
2024-07-12 13:28:23,176 ERROR TaskExecutor CombatCheck:target_enemy failed, break out of combat 
2024-07-12 13:29:34,083 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-12 13:30:38,455 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-12 13:31:15,645 ERROR TaskExecutor TaskExecutor:Farm Echo in Dungeon exception Traceback (most recent call last):
  File "ok\task\TaskExecutor.py", line 285, in execute
  File "src\task\FarmEchoTask.py", line 58, in run
  File "src\task\BaseCombatTask.py", line 247, in walk_until_f
  File "src\task\BaseCombatTask.py", line 216, in send_key_and_wait_f
ok.task.TaskExecutor.CannotFindException: cant find the f to enter

**Comment by kunkun9527** [comment]
刚更新了0.036，貌似有所改善，我今天挂机一晚看看效果

**Comment by kunkun9527** [comment]
又出现了

2024-07-12 21:14:53,842 ERROR TaskExecutor BaseCombatTask:combat check not in combat 
2024-07-12 21:15:41,669 ERROR TaskExecutor CombatCheck:keep_boss_text_white cant find text with the correct color 
2024-07-12 21:15:58,048 ERROR TaskExecutor BaseCombatTask:not in team while switching chars_Jinhsi_T_to_Verina_F, 0.0 
2024-07-12 21:16:31,785 ERROR TaskExecutor TaskExecutor:Farm Echo in Dungeon exception Traceback (most recent call last):
  File "ok\task\TaskExecutor.py", line 285, in execute
  File "src\task\FarmEchoTask.py", line 58, in run
  File "src\task\BaseCombatTask.py", line 247, in walk_until_f
  File "src\task\BaseCombatTask.py", line 216, in send_key_and_wait_f
ok.task.TaskExecutor.CannotFindException: cant find the f to enter

**Comment by ok-oldking** [comment]
可以试试最新版, 卡在月卡界面短期内没计划解决

**Comment by kunkun9527** [comment]
> 可以试试最新版, 卡在月卡界面短期内没计划解决

今天更新了0.038，运行了一次，还是一样的问题。

2024-07-13 12:26:40,374 ERROR TaskExecutor TaskExecutor:Farm Echo in Dungeon exception Traceback (most recent call last):
  File "ok\task\TaskExecutor.py", line 285, in execute
  File "src\task\FarmEchoTask.py", line 58, in run
  File "src\task\BaseCombatTask.py", line 247, in walk_until_f
  File "src\task\BaseCombatTask.py", line 216, in send_key_and_wait_f
ok.task.TaskExecutor.CannotFindException: cant find the f to enter

我可以给你说说我的运行环境。WIN10 22H2，然后我有两个屏幕，平时用左边屏幕干活，鸣潮和脚本就放在右边屏幕挂机。
