### ISSUE TITLE
[BUG]朔雷声骸离远点就不捡，乌龟破防今夕E之后就不再战斗并开始切地图

### ISSUE THREAD

**Issue by leohoo633** [ok-oldking/ok-wuthering-waves#31]
描述错误:
朔雷声骸爆在面前一点就不捡，乌龟破防倒地后，今夕E龙喷完之后就不再战斗，并开始切地图打下一个boss，另外乌龟战斗过程中也存在乌龟倒地后三个角色丢失锁定一路A出boss场地（亲测与今夕无关），之后判定战斗结束开始切地图。

复现步骤 按照以下步骤复现行为：

自动战斗开，声骸拾取开，月卡跳过开，刷大世界4Cboss声骸开；配队：今夕/暗主/忌炎，长离/莫特斐，维里奈

截图 :
暂无

是否必现:
大概率

录屏:
暂无

脚本软件版本：
v.0.1.43

windows操作系统:
Windows 10 家庭中文版 22H2 19045.3693

上传日志:
[ok-ww.zip](https://github.com/user-attachments/files/16398882/ok-ww.zip)

感谢作者大大勤恳更新！另外希望加入战斗结束后视角转动或者转圈跑的操作来提升声骸捡取准确度。

**Comment by enjoy05sky** [comment]
我也遇到同样的问题，乌龟boss大概率会不再战斗，堆栈如下：
2024-07-27 23:12:31,845 ERROR TaskExecutor CombatCheck:target_enemy failed, break out of combat 
2024-07-27 23:12:31,862 ERROR TaskExecutor BaseCombatTask:sleep check not in combat 
2024-07-27 23:13:43,524 ERROR TaskExecutor BaseCombatTask:too long clicking a liberation 
2024-07-27 23:14:03,863 ERROR TaskExecutor TaskExecutor:Farm World Boss(Must Drop a WayPoint on the Boss First) exception Traceback (most recent call last):
  File "ok\task\TaskExecutor.py", line 282, in execute
  File "src\task\FarmWorldBossTask.py", line 162, in run
  File "src\task\FarmWorldBossTask.py", line 78, in teleport_to_boss
Exception: can't find the boss proceeds

**Comment by ok-oldking** [comment]
试试最新版
