### ISSUE TITLE
[BUG]夜里挂机刷声骸 早上看到游戏已经退出

### ISSUE THREAD

**Issue by B1ngFeng** [ok-oldking/ok-wuthering-waves#54]
描述错误:
晚上挂机刷声骸，早上看游戏已经退出，还弹了几个内存的错误。
昨天晚上刷角，早上也是游戏已经退出，不过没有弹内存错误。
游戏是D3D11运行的，昨天改了今天没改画质文件，1080P 60帧，游戏内画质选项基本都最低，开了DLSS，配置是3600+2060S，内存4*8G 3200MHz Gear1。

复现步骤 按照以下步骤复现行为：

1. 晚上挂机刷大世界4C声骸，正常运行
2. 早上起来看到游戏不在运行

截图 :
有个这个内存的问题，还有个chrome的内存问题，没截。
![Snipaste_2024-08-04_12-02-53](https://github.com/user-attachments/assets/5b622b34-c0c0-4012-9fbb-786c5717f25d)

是否必现:
大概率

录屏:
无

脚本软件版本：
0.1.71（最新）

windows操作系统:
Windows 10 专业版 22H2 19045.3393

上传日志:
[ok-script.log](https://github.com/user-attachments/files/16486263/ok-script.log)
[ok-script_error.log](https://github.com/user-attachments/files/16486265/ok-script_error.log)

**Comment by ok-oldking** [comment]
看日志应该是类似熄屏或者睡眠 没法截图

**Comment by B1ngFeng** [comment]
> 看日志应该是类似熄屏或者睡眠 没法截图

怪，我的电源计划是AMD装驱动自带的Ryzen Balanced，我看里面设置，是从不进入睡眠或休眠模式的，但是关闭显示器是20分钟，是这个的问题吗？

我看日志的23540行：
> 2024-08-04 05:32:49,724 ERROR Dummy-1 WindowsGraphicsCaptureMethod:TryGetNextFrame error Unable to allocate 7.91 MiB for an array with shape (1080, 1920, 4) and data type uint8 
2024-08-04 05:32:49,725 INFO Dummy-1 WindowsGraphicsCaptureMethod:destroy windows capture
2024-08-04 05:32:52,717 INFO TaskExecutor WindowsGraphicsCaptureMethod:init windows capture
2024-08-04 05:32:58,813 ERROR TaskExecutor WindowsGraphicsCaptureMethod:start_or_stop failed: title_None_Client-Win64-Shipping.exe_1920x1080_398014_1_False Traceback (most recent call last):
  File "ok\capture\windows\WindowsGraphicsCaptureMethod.py", line 143, in start_or_stop
  File "ok\capture\windows\WindowsGraphicsCaptureMethod.py", line 173, in create_device
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2005532292] Windows Error 0x8876017c

> 2024-08-04 05:32:58,914 INFO TaskExecutor WindowsGraphicsCaptureMethod:init windows capture
2024-08-04 05:32:58,942 ERROR TaskExecutor WindowsGraphicsCaptureMethod:start_or_stop failed: title_None_Client-Win64-Shipping.exe_1920x1080_398014_1_False Traceback (most recent call last):
  File "ok\capture\windows\WindowsGraphicsCaptureMethod.py", line 143, in start_or_stop
  File "ok\capture\windows\WindowsGraphicsCaptureMethod.py", line 173, in create_device
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -2147024882] 内存资源不足，无法完成此操作。

不是内存的问题吗？
