### ISSUE TITLE
[BUG]声骸五合一功能，在遇到磐石守卫等类似技能描述过长所以无法读取到合鸣效果，导致无法识别，从而终止合成

### ISSUE THREAD

**Issue by liuqq58** [ok-oldking/ok-wuthering-waves#60]
请先挨个检查,[常见问题](https://github.com/ok-oldking/ok-wuthering-waves/readme/faq.md)

描述错误:
关于声骸五合一功能，在遇到磐石守卫等类似技能描述过长所以无法读取到合鸣效果，导致无法识别，从而终止合成，报错

复现步骤 按照以下步骤复现行为：
合成中遇到技能描述过长，就会提示需要修改简介显示，实际已经是缩写的了

截图 :
提示确实过短没有截图到，但是应该很容易复现

是否必现:
必现

录屏:
无

脚本软件版本：
1.8正式版

windows操作系统:
Windows 10 22h2

上传日志:
  File "ok\task\TaskExecutor.py", line 286, in execute
  File "src\task\FarmEchoTask.py", line 48, in run
  File "src\task\BaseCombatTask.py", line 60, in combat_once
  File "ok\task\ExecutorOperation.py", line 280, in wait_until
  File "ok\task\TaskExecutor.py", line 235, in wait_condition
ok.task.TaskExecutor.WaitFailedException

2024-08-06 08:23:40,056 ERROR TaskExecutor FiveToOneTask:无法识别声骸套装, 需要打开角色声骸界面,右上角点击切换一下简述 
2024-08-06 08:24:01,213 ERROR TaskExecutor TaskExecutor:在数据坞五合一界面启动 exception Traceback (most recent call last):
  File "ok\task\TaskExecutor.py", line 286, in execute
  File "src\task\FiveToOneTask.py", line 73, in run
  File "src\task\FiveToOneTask.py", line 121, in loop_merge
Exception: 请在5合1界面开始,并保持声骸未添加状态

2024-08-06 08:24:42,903 ERROR TaskExecutor FiveToOneTask:无法识别声骸套装, 需要打开角色声骸界面,右上角点击切换一下简述 
2024-08-06 08:33:46,298 ERROR update_window_size HwndWindow:ok.gui.executor.pause pos_invalid: (-32000, -32000, 0, 0) 

该功能建议，能否点击每个声骸后，读取每个声骸头像的的右下角的属性小图标，每个小图标的颜色都是不一样的，这样只要识别颜色即可，这样只要读取声骸头像的的右下角的属性小图标即可确定合鸣效果，然后匹配主属性词条内容即可，不知道是否可行
或者只能在合成过程中针对技能描述过长的，增加一次下拉滑动操作即可

**Comment by ok-oldking** [comment]
卡住的地方 点截图测试 上传一张

**Comment by liuqq58** [comment]
> 卡住的地方 点截图测试 上传一张

![WindowsGraphicsCaptureMethod_1600x900_title_None_Client-Win64-Shipping exe_1600x900_2492102_1_False_1722910479561 755_original](https://github.com/user-attachments/assets/c3680e78-41b2-48e8-8926-cd59f44f5bd9)
 这个也遇到了  还不是磐石守卫了
